### ISSUE TITLE
When running the skill as standalone with ovos-core 0.0.8a15 fails

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/skill-ovos-date-time#22]
```
2023-05-03 01:56:04.789 - OVOS - ovos_plugin_manager.utils:find_plugins:94 - ERROR - Failed to load plugin entry point EntryPoint(name='skill-ovos-date-time.openvoiceos', value='skill_ovos_date_time:TimeSkill', group='ovos.plugin.skill')
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ovos_plugin_manager/utils/__init__.py", line 90, in find_plugins
    entrypoints[entry_point.name] = entry_point.load()
                                    ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/importlib_metadata/__init__.py", line 210, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ovos/.local/lib/python3.11/site-packages/skill_ovos_date_time/__init__.py", line 24, in <module>
    import mycroft.audio
  File "/usr/lib/python3.11/site-packages/mycroft/audio/__init__.py", line 15, in <module>
    from ovos_audio.utils import wait_while_speaking, is_speaking, stop_speaking
Traceback (most recent call last):
  File "/usr/bin/ovos-skill-launcher", line 8, in <module>
ModuleNotFoundError: No module named 'ovos_audio'
    sys.exit(_launch_script())
             ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 572, in _launch_script
    skill.run()
  File "/usr/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 526, in run
    self._connect_to_core()
  File "/usr/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 508, in _connect_to_core
    self.load_skill()
  File "/usr/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 521, in load_skill
    self._launch_plugin_skill()
  File "/usr/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 539, in _launch_plugin_skill
    raise ValueError(f"unknown skill_id: {self.skill_id}")
ValueError: unknown skill_id: skill-ovos-date-time.openvoiceos
```

```
adapt-parser==1.0.0
certifi==2022.12.7
charset-normalizer==3.1.0
click==8.1.3
colour==0.1.5
combo-lock==0.2.5
decorator==5.1.1
fann2==1.0.7
filelock==3.12.0
future==0.18.3
geocoder==1.38.1
idna==3.4
importlib-metadata==6.6.0
json-database==0.7.0
kthread==0.2.3
langcodes==3.3.0
markdown-it-py==2.2.0
mdurl==0.1.2
memory-tempfile==2.2.3
numpy==1.24.3
ovos-backend-client==0.0.7a5
ovos-bus-client==0.0.4a6
ovos-config==0.0.9a1
ovos-core==0.0.8a15
ovos-lingua-franca==0.4.8a1
ovos-plugin-manager==0.0.23a10
ovos-skill-date-time==0.2.2
ovos-utils==0.0.33a5
ovos-workshop==0.0.12a24
packaging==23.1
padacioso==0.1.2
padaos==0.1.10
padatious==0.4.8
pexpect==4.8.0
ptyprocess==0.7.0
pyee==8.2.2
Pygments==2.15.1
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
quebra-frases==0.3.7
rapidfuzz==3.0.0
ratelim==0.1.6
requests==2.29.0
rich==13.3.5
rich-click==1.6.1
simplematch==1.3
six==1.16.0
timezonefinder==5.2.0
tzlocal==5.0b2
urllib3==1.26.15
watchdog==2.3.1
webcolors==1.13
websocket-client==1.5.1
xxhash==3.2.0
zipp==3.15.0
```

**Comment by goldyfruit** [comment]
I'm wondering if it's not related to the requirements _(not sure at all)_.

```
ovos-utils~=0.0, >=0.0.28
ovos_workshop~=0.0, >=0.0.11
```

For `ovos-skill-wkipedia` (which is working), the requirements are a bit higher.

```
ovos-utils~=0.0, >=0.0.28a4
ovos_workshop~=0.0, >=0.0.11a4
```

**Comment by JarbasAl** [comment]
the skill has some weird usages of mycroft.audio.wait_while_speaking() that need to be refactored to import from ovos_utils.signal instead

it will also work if ovos-audio is installed, you only run into it because of using minimal containers

**Comment by goldyfruit** [comment]
> it will also work if ovos-audio is installed, you only run into it because of using minimal containers

Indeed, adding `ovos-audio` fixed the issue.

**Comment by JarbasAl** [comment]
leaving the issue open as the refactor should still be done

**Comment by goldyfruit** [comment]
> leaving the issue open as the refactor should still be done

Oops, the commit closed the issue. :+1:

**Comment by goldyfruit** [comment]
Fixed by https://github.com/OpenVoiceOS/skill-ovos-date-time/pull/24
