### ISSUE TITLE
"what time is it" in French returns an error

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/skill-ovos-date-time#23]
When asking `quelle heure est-il` in French, it returns this trace:
```
2023-05-14 17:42:43.636 - skill-ovos-date-time.openvoiceos - ERROR - 'temps'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ovos_utils/messagebus.py", line 554, in wrapper
    handler(message)
  File "/home/ovos/.local/lib/python3.11/site-packages/skill_ovos_date_time/__init__.py", line 424, in handle_current_time_simple
    self.handle_query_time(message)
  File "/home/ovos/.local/lib/python3.11/site-packages/skill_ovos_date_time/__init__.py", line 409, in handle_query_time
    self.speak_dialog("time.current", {"time": current_time})
  File "/usr/lib/python3.11/site-packages/ovos_workshop/skills/base.py", line 1730, in speak_dialog
    self.dialog_renderer.render(key, data),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ovos_utils/dialog.py", line 94, in render
    line = line.format(**context)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'temps'
```

**Comment by emphasize** [comment]
All translations were updated a _should_ work as intended

**Comment by goldyfruit** [comment]
Indeed no more issue but translation need some work.
