### ISSUE TITLE
`AttributeError: 'EnclosureAPI' object has no attribute 'display_manager'`

### ISSUE THREAD

**Issue by Ramblurr** [OpenVoiceOS/skill-ovos-date-time#34]
Running vanilla ovos-docker this skill fails with:

```
ovos_messagebus              | 2023-09-12 12:07:30.220 - bus - ovos_messagebus.event_handler:on_message:50 - DEBUG - skill-ovos-date-time.openvoiceos:skill-ovos-date-time.openvoiceosupdate_display source: [] destination: []
ovos_skill_date_time         | 2023-09-12 12:07:30.224 - OVOS - ovos_utils.events:wrapper:116 - ERROR - 'EnclosureAPI' object has no attribute 'display_manager'
ovos_skill_date_time         | Traceback (most recent call last):
ovos_skill_date_time         |   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/events.py", line 114, in wrapper
ovos_skill_date_time         |     handler(message)
ovos_skill_date_time         |   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_date_time/__init__.py", line 325, in update_display
ovos_skill_date_time         |     if (force is True) or self._is_display_idle():
ovos_skill_date_time         |                           ^^^^^^^^^^^^^^^^^^^^^^^
ovos_skill_date_time         |   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_date_time/__init__.py", line 309, in _is_display_idle
ovos_skill_date_time         |     return self.enclosure.display_manager.get_active() == ''
ovos_skill_date_time         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ovos_skill_date_time         | AttributeError: 'EnclosureAPI' object has no attribute 'display_manager'
ovos_skill_date_time         | 2023-09-12 12:07:30.224 - OVOS - ovos_utils.events:on_error:289 - ERROR - An error occurred executing the scheduled event: 'EnclosureAPI' object has no attribute 'display_manager'
```

**Comment by JarbasAl** [comment]
closed as part of general cleanup via #38 and #37
