### ISSUE TITLE
ModuleNotFoundError: format module of language 'fr' is not currently loaded.

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/skill-ovos-date-time#57]
```
query': 'de quand date le 1er jeu de société', 'is_ocp_conf': 0.4, 'conf': 0.4}, skill_id='ovos.common_play', utterance='de quand date le 1er jeu de société')
2024-10-26 12:37:02.253 - skills - ovos_core.intent_services:converse:120 - WARNING - Deprecation version=1.0.0. Caller=concurrent.futures.thread:58. direct access to self.converse is deprecated, pipelines are in the progress of being replaced with plugins
2024-10-26 12:39:22.224 - skills - padacioso:calc_intent:240 - INFO - No match
2024-10-26 12:39:22.233 - skills - ovos_core.intent_services:handle_utterance:481 - INFO - padatious_high match: IntentMatch(intent_service='Padatious', intent_type='skill-ovos-date-time.openvoiceos:what.time.is.it.intent', intent_data={}, skill_id='skill-ovos-date-time.openvoiceos', utterance='quelle heure est-il')
2024-10-26 12:39:22.235 - skills - ovos_core.intent_services:converse:120 - WARNING - Deprecation version=1.0.0. Caller=concurrent.futures.thread:58. direct access to self.converse is deprecated, pipelines are in the progress of being replaced with plugins
2024-10-26 12:39:22.334 - skills - ovos_utils.file_utils:resolve_resource_file:194 - WARNING - Deprecation version=0.1.0. Caller=ovos_utils.dialog:166. Expected a dict config and got None.
2024-10-26 12:39:22.356 - skill-ovos-date-time.openvoiceos - ERROR - format module of language 'fr' is not currently loaded.
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/events.py", line 78, in wrapper
    handler(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_date_time/__init__.py", line 295, in handle_current_time_simple
    self.handle_query_time(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_date_time/__init__.py", line 291, in handle_query_time
    self.speak_time("time.current", location=location)
  File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_date_time/__init__.py", line 275, in speak_time
    current_time = self.get_spoken_time()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_date_time/__init__.py", line 210, in get_spoken_time
    s = nice_time(dt, lang=self.lang, speech=True,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/lingua_franca/internal.py", line 620, in call_localized_function
    return _call_localized_function(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/lingua_franca/internal.py", line 550, in _call_localized_function
    raise ModuleNotFoundError(_module_name +
ModuleNotFoundError: format module of language 'fr' is not currently loaded.
```

**Comment by goldyfruit** [comment]
The issue was a wrong lang code, it should be `fr-FR` and not `fr_FR`.
